tap "homebrew/bundle"
brew "duti"
brew "exiftool"
brew "ffmpeg"
brew "jq"
brew "links"
brew "lynx"
brew "md5sha1sum"
brew "qpdf"
brew "telnet"
brew "tmux"
brew "uade"
# Pillow replaces Python PIL
brew "pillow"
